@startuml
class Hello1 {
  +myMethods()
}

class Hello2 {
  +hiddenMethod()
}

class Hello3 <<Serializable>> {
String name
}

hide members
hide <<Serializable>> circle
show Dummy1 methods
show <<Serializable>> fields
@enduml
